"""
COIN:OPERATED JRPG - Procedural Graphics System
All graphics and animations generated by code

SNES-Style System: Authentic 16-bit JRPG visuals
"""

# Original procedural graphics system
from .sprite_generator import SpriteGenerator
from .animation_generator import AnimationGenerator
from .ui_generator import UIGenerator
from .effect_generator import EffectGenerator
from .environment_generator import EnvironmentGenerator
from .color_palette import ColorPalette

# SNES-style graphics system (16-bit JRPG aesthetic)
from .snes_palette import SNESPalette
from .snes_sprite_generator import SNESSpriteGenerator
from .snes_tilemap import SNESTileGenerator, SNESMapRenderer
from .snes_battle_screen import SNESBattleScreen
from .snes_ui import SNESUI
from .snes_renderer import SNESGameRenderer

__all__ = [
    # Original system
    'SpriteGenerator',
    'AnimationGenerator', 
    'UIGenerator',
    'EffectGenerator',
    'EnvironmentGenerator',
    'ColorPalette',
    
    # SNES system
    'SNESPalette',
    'SNESSpriteGenerator',
    'SNESTileGenerator',
    'SNESMapRenderer',
    'SNESBattleScreen',
    'SNESUI',
    'SNESGameRenderer',
]
